### ISSUE TITLE
can't evaluate field Release in type []interface {}

### ISSUE THREAD

**Issue by cch0** [technosophos/common-chart#5]
This is what I did.

## 1. Followed the instruction to create a new chart
`helm create mychart`

## 2. add common 
`cd mychart/charts`
`helm fetch common/common`

Note that the last command (helm fetch) is different from what is described in the instruction. If I used
`helm fetch common`
I then got
`Error: Non-absolute URLs should be in form of repo_name/path_to_chart, got: common`

## 3. add a some.yaml file under mychart/templates/

```
{{- template "common.deployment" (list . "mychart.deployment") -}}
{{- define "mychart.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "mychart.deployment.container") }}
{{- end -}}
{{- define "mychart.deployment.container" -}}
## Define overrides for your Container here, e.g.
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80
{{- end -}}
```

## 4. ran this command
`helm template --name myrelease mychart`

and then got
`Error: render error in "mychart/templates/some.yaml": template: mychart/charts/common/templates/_common.tpl:17:27: executing "common.fullname" at <.Release.Name>: can't evaluate field Release in type []interface {}`

## Question:
Where did I do wrong?
