### ISSUE TITLE
Simplify unique name configurations for multiple deployments

### ISSUE THREAD

**Issue by kivagant-ba** [technosophos/common-chart#6]
Originally you suggest the following syntax to extend default names for different resources:

```yaml
{{- define "my.fullname" -}}
  {{ template "common.fullname" . }}-my-stuff
{{- end -}}
```

But this is inconvenient. When you need to refer to different configuration values for different resources, you have to use something like [in the DataDog's example](https://github.com/helm/charts/blob/master/stable/datadog/templates/agent-clusterchecks-deployment.yaml#L58):

```yaml
{{- if .Values.my-chart-app-my-stuff.env }}
{{ toYaml .Values.my-chart-app-my-stuff.env | indent 10 }}
{{- end }}
```

As you see, the code can't be reused in templates.
But actually there's a trick that may help to make it better. Let's change `common.fullname' a little bit:

```
{{- define "common.fullname"}}
  {{- $global := default (dict) .Values.global -}}
  {{- $base := default (printf "%s-%s" .Release.Name .Chart.Name) .Values.fullnameOverride -}}
  {{- if (.appName) -}}
    {{- $base = .appName -}}
  {{- else -}}
  {{- end -}}
  {{- $gpre := default "" $global.fullnamePrefix -}}
  {{- $pre := default "" .Values.fullnamePrefix -}}
  {{- $suf := default "" .Values.fullnameSuffix -}}
  {{- $gsuf := default "" $global.fullnameSuffix -}}
  {{- $name := print $gpre $pre $base $suf $gsuf -}}
  {{- $name | lower | trunc 54 | trimSuffix "-" -}}
{{- end -}}
```

Now it checks if `.appName` is set in global scope. And now we can set the name differently in different deployments/services/etc:

```yaml
{{- $_ := set . "appName" "my-chart-app-my-stuff" -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
```

And in the same time in `values.yaml` we can set the structure:
```yaml

resources:
  my-chart-app-my-stuff:
    requests:
      memory: 512Mi
    limits:
      memory: 512Mi

```

And use it in the same deployment using the `.appName`:

```
# ...
          resources:
{{ index .Values "resources" .appName | toYaml | trim | indent 12 }}
```

So the key difference is that `.Values.fullnameOverride` can be used for the entire chart but `.appName` can be set for a specific resource individually which makes templates more clear, reusable and flexible.

P.S.: I know about https://github.com/helm/charts/tree/master/incubator/common but I guess it's better to discuss the chart here than in that repo with tons of issues.
